services:
  - type: web
    name: pointsfam-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_USER
        value: your-mysql-user
      - key: DB_PASSWORD
        value: your-mysql-password
      - key: DB_NAME
        value: pointsfam
      - key: DB_PORT
        value: 3306 